services:
  loki:
    image: grafana/loki:2.9.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      -  loki_data:/loki            
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - loki
  caddy:
    image: caddy:2.8.4-alpine
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - loki
    volumes:
      - caddy_logs:/var/log/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile  
networks:
  loki:
volumes:
  caddy_logs:
  loki_data:      